# Dockerfile.frontend
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONPATH=/app
ENV PORT=8501
EXPOSE 8501

CMD ["sh", "-c", "streamlit run frontend/app.py --server.address=0.0.0.0 --server.port=$PORT"]
