from semantic_kernel.connectors.azure_ai_search import AzureAISearchCollection
from backend.data_models import PodcastEpisode

podcast_collection = AzureAISearchCollection(record_type=PodcastEpisode)
