# .github/workflows/deploy.yml

name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest -f Dockerfile.backend .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest -f Dockerfile.frontend .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest

      - name: Deploy Backend to ACA
        run: |
          az containerapp update \
            --name sysk-ai-backend \
            --resource-group ai-sysk-demo \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest

      - name: Deploy Frontend to ACA
        run: |
          az containerapp update \
            --name sysk-ai-frontend \
            --resource-group ai-sysk-demo \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
